[db]
shadow_port = 65432

[functions.send-event-staff-assignment-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-event-staff-assignment-email/deno.json"
entrypoint = "./functions/send-event-staff-assignment-email/index.ts"